### ISSUE TITLE
[Question] What's the future of this plugin past IJ 2020.3 release?

### ISSUE THREAD

**Issue by ChrisCarini** [gilday/dark-mode-sync-plugin#26]
I was reading JetBrain's blog post today on [IntelliJ IDEA 2020.3 EAP](https://blog.jetbrains.com/idea/2020/09/intellij-idea-2020-3-eap/) which covers some of the features coming to the next release.

One of the features highlighted in this post is `IDE theme synced with OS settings` which seems to natively bring to IJ the feature this plugin brings.

I was just curious what this means for the `Dark Mode Sync` plugin. Will this be kept around to continue to bring the feature / functionality to older versions of IJ / other IDEs?

**Comment by gilday** [comment]
I too saw that! I hoped this plugin would ultimately be a temporary workaround, and I am excited that this functionality will be built into IntelliJ now.

Right now, I do not intend to update the plugin's XML manifest to indicate support for 2020.3, because 2020.3 should prefer the built in functionality. If there are feature gaps between the built-in functionality and what this plugin offers, then I will reconsider.

For now, I intend to maintain this plugin for legacy versions of IntelliJ. I have a soft spot for Android Studio users, and I don't want to put them out while they do not yet have an IDE built on 2020.3.

**Comment by szhorvat** [comment]
> If there are feature gaps between the built-in functionality and what this plugin offers, then I will reconsider.

@gilday It appears that the built-in functionality only changes the GUI theme, but not the editor theme. When it switches to dark, all the GUI elements go dark, but the editor colour scheme stays light.  Am I missing an obvious way to make the editor theme sync too? If not, please consider making this great plugin compatible with 2020.3.

**Comment by gilday** [comment]
@szhorvat this plug-in currently does not have that functionality neither. The issue for building color scheme support is #23

**Comment by szhorvat** [comment]
@gilday I'm quite confused, as it most definitely did switch the colour scheme for me. Otherwise I would not be here complaining. And it is definitely _your_ (i.e. this) plugin—I just double checked. I guess I should downgrade IntelliJ and try to figure out why that worked at all. Maybe IntelliJ itself had a way to tie the colour scheme to the theme? Do you have any idea why it switched both for me?

**Comment by gilday** [comment]
@szhorvat were you able to determine if the plugin switched both color scheme and appearance on an earlier IntelliJ (e.g. 2020.2)?

**Comment by szhorvat** [comment]
@gilday I'm still quite confused. Here's what happened:

I reverted to 2020.2 and found that both appearance and colour scheme are switched. I disabled the plugin and verified that IntelliJ is doing this: if I switch the appearance, it also switches the colour scheme. It had nothing to do with the plugin. Then I re-upgraded to 2020.3 and unlike before, now I see the same behaviour there: switching appearance also switches colour scheme. _But I still could not find what setting controls this_, either in 2020.2 or 2020.3. If you can figure this out, please let me know.

Anyway, I'm happy as now both are switched, even with the built-in setting to sync with the OS appearance.

**Comment by gilday** [comment]
Hmmm that is odd. I'm glad you have it working now 👍
